const SANGHA_DATA = {
    data: {
            "1": {
              "id": 1,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "2:30AM-3:30AM",
              "name": "Daily Morning Meditation",
              "teacher": "Martin Aylward",
              "organization": "Sangha Live",
              "orgUrl": "https://sangha.live/",
              "Registration": "Register Here",
              "Registration URL": "https://sangha.live/sunday_sangha/daily-meditation-30-03-2020-uk-eu/"
            },
            "2": {
              "id": 2,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "7:30-8:15 AM",
              "name": "Daily Meditation, Mon-Fri",
              "teacher": "Karolynn Coleman",
              "organization": "Insight Meditation Center Washington",
              "orgUrl": "https://imcw.org/",
              "Registration": "Zoom"
            },
            "3": {
              "id": 3,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "7:15-8:15 AM",
              "name": "Morning Meditation",
              "teacher": "Various",
              "organization": "Brooklyn Zen Center",
              "orgUrl": "https://brooklynzen.org/online-dharma-offerings/",
              "Registration": "Zoom",
              "Registration URL": "https://zoom.us/j/173111572"
            },
            "4": {
              "id": 4,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "1899-12-30T14:00:00.000Z",
              "name": "Daily Morning Meditation Recording Available",
              "teacher": "Martin Aylward",
              "organization": "Sangha Live",
              "orgUrl": "https://sangha.live/",
              "Registration": "Register Here",
              "Registration URL": "https://sangha.live/daily/?utm_source=Sangha+Live&utm_campaign=9f62c9e8da-EMAIL_CAMPAIGN_2020_03_20_02_52_COPY_01&utm_medium=email&utm_term=0_a43a640cb8-9f62c9e8da-303838097"
            },
            "5": {
              "id": 5,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "9:00-10:00 AM",
              "name": "Morning Meditation, Mon-Fri",
              "teacher": "Linda Naini, Jennifer Jordan, Jane Jackson, Jennifer Stanley, Steve Zappalla",
              "organization": "Insight Meditation Center Washington",
              "orgUrl": "https://imcw.org/",
              "Registration": "Zoom"
            },
            "6": {
              "id": 6,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "10:00-10:30 AM",
              "name": "Morning Meditation",
              "teacher": "Rachel Lewis",
              "organization": "British Columbia Insight Meditation Society",
              "orgUrl": "http://bcims.org/",
              "Registration": "Zoom"
            },
            "7": {
              "id": 7,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "10:00-10:30 AM",
              "name": "Morning Meditation",
              "teacher": "Mary Stancavage",
              "organization": "Undefended Dharma",
              "orgUrl": "https://marystancavage.org/",
              "Registration": "Zoom"
            },
            "8": {
              "id": 8,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "10:00-11:00 AM",
              "name": "Daily Sunrise Nature Meditation (M-F)",
              "teacher": "Mark Coleman",
              "organization": "Mark Coleman",
              "orgUrl": "http://www.markcoleman.org/",
              "Registration": "Register Here",
              "Registration URL": "https://markcoleman.org/event/free-online-daily-sunrise-nature-meditation/"
            },
            "9": {
              "id": 9,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "10:00-10:30 AM",
              "name": "Sitting and Dharmette",
              "teacher": "Gil Fronsdal",
              "organization": "Insight Meditation Center",
              "orgUrl": "http://www.insightmeditationcenter.org/",
              "Registration": "YouTube"
            },
            "10": {
              "id": 10,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "10:00-10:30 AM",
              "name": "Morning Meditation",
              "teacher": "Will Kabat-Zinn",
              "organization": "Sunday Sangha",
              "orgUrl": "https://sundaysangha.net/",
              "Registration": "Zoom"
            },
            "11": {
              "id": 11,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "10:00-10:40 AM",
              "name": "Morning Meditation",
              "teacher": "Various",
              "organization": "Rocky Mountain Ecodharma Retreat Center",
              "Registration": "Contact for Zoom info",
              "Registration URL": "https://rockymountainecodharmaretreatcenter.org/contact/"
            },
            "12": {
              "id": 12,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "10:00-10:45 AM",
              "name": "Daily Meditation",
              "teacher": "Various Teachers",
              "organization": "Center for Mindful Self-Compassion",
              "orgUrl": "https://centerformsc.org",
              "Registration": "Register Here",
              "Registration URL": "https://www.signupgenius.com/go/10c0c4aa4af29ab9-free"
            },
            "13": {
              "id": 13,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "10:00-10:45 AM",
              "name": "Morning Meditation, Mon-Sat",
              "teacher": "Robert Beatty",
              "organization": "Portland Insight",
              "orgUrl": "http://www.portlandinsight.org/",
              "Registration": "Zoom"
            },
            "14": {
              "id": 14,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "10:30-11:00 AM",
              "name": "Morning Community Sit - Guided Meditation",
              "teacher": "Beth Sternlieb",
              "organization": "Insight L.A.",
              "orgUrl": "https://insightla.org/",
              "Registration": "Zoom"
            },
            "15": {
              "id": 15,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "10:30-11:15 AM",
              "name": "Bridging the Social Distancing Divide",
              "teacher": "Bill and Susan Morgan",
              "organization": "Buddhist Inquiry",
              "orgUrl": "https://www.buddhistinquiry.org/",
              "Registration": "Zoom"
            },
            "16": {
              "id": 16,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "10:30-11:15 AM",
              "name": "Morning Sit",
              "teacher": "Various Teachers",
              "organization": "SF Dharma Collective",
              "orgUrl": "https://sites.google.com/view/sfdharmacollective/home?authuser=0",
              "Registration": "Zoom"
            },
            "17": {
              "id": 17,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "10:45-11:30 AM",
              "name": "Meditation, Mon-Fri",
              "teacher": "Jessica Escobedo, Enrique Collazo",
              "Registration": "Zoom"
            },
            "18": {
              "id": 18,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "11:00AM -12:00 PM",
              "name": "Daily Morning Meditation",
              "teacher": "Caverly Morgan",
              "organization": "Sangha Live",
              "orgUrl": "https://sangha.live/",
              "Registration": "Register Here",
              "Registration URL": "https://sangha.live/sunday_sangha/daily-meditation-30-03-2020-us/"
            },
            "19": {
              "id": 19,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "10:30-10:55 AM",
              "name": "Morning Meditation, Mon-Sat",
              "teacher": "George Haas",
              "organization": "Metta Group",
              "orgUrl": "https://www.mettagroup.org/",
              "Registration": "Register Here"
            },
            "20": {
              "id": 20,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "10:30-11:15 AM",
              "name": "Sitting in Place, Mon-Fri",
              "teacher": "Andrea Vecchione",
              "organization": "SF Dharma Collective",
              "orgUrl": "https://sites.google.com/view/sfdharmacollective/home?authuser=0",
              "Registration": "Zoom"
            },
            "21": {
              "id": 21,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "8:45-9:30 AM",
              "name": "Daily Sit",
              "teacher": "T Maes, Devon Cresci",
              "organization": "Anthony Maes",
              "orgUrl": "http://www.anthonymaes.com/classes",
              "Registration": "Zoom",
              "Registration URL": "https://zoom.us/j/401782826"
            },
            "22": {
              "id": 22,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "12:00PM -1:00 PM",
              "name": "Garrison Institute Daily Meditation, Mon-Fri",
              "teacher": "Jane Kolleeny & Guests",
              "organization": "Garrison Institute",
              "orgUrl": "http://www.garrisoninstitute.org/",
              "Registration": "Register Here"
            },
            "23": {
              "id": 23,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "12:00 - 12:30 PM",
              "name": "Daily Meditation (in French)",
              "teacher": "Roxanne Dault",
              "organization": "True North Insight",
              "Registration": "YouTube",
              "Registration URL": "https://www.youtube.com/watch?v=cLPB3jKF8r8"
            },
            "24": {
              "id": 24,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "12:00-1:00 PM",
              "name": "Midday Sangha",
              "teacher": "Various Teachers",
              "organization": "East Bay Meditation Center",
              "orgUrl": "https://eastbaymeditation.org/",
              "Registration": "Zoom"
            },
            "25": {
              "id": 25,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "12:00-1:00 PM",
              "name": "Daily Midday Sangha",
              "teacher": "Ray Manyoky",
              "organization": "Frederick Meditation Center",
              "orgUrl": "https://frederickmeditation.com/",
              "Registration": "Zoom"
            },
            "26": {
              "id": 26,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "12:00-1:00 PM",
              "name": "Daily Meditation",
              "teacher": "Various Teachers",
              "organization": "Insight Meditation Center of Charlottesville",
              "orgUrl": "http://www.imeditation.org/",
              "Registration": "Zoom",
              "Registration URL": "http://www.imeditation.org/event-3796918"
            },
            "27": {
              "id": 27,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "1:00-2:00 PM",
              "name": "Nalanda Institute & Tibet House US Weekday Lunchtime Meditation, Mon-Fri",
              "teacher": "Various Teachers: \nWeds 4/8: Abby Eletz",
              "organization": "Nalanda Institute & Tibet House US",
              "Registration": "Register Here",
              "Registration URL": "https://bit.ly/march-lunchtime-meditation"
            },
            "28": {
              "id": 28,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "1:00-2:00 PM",
              "name": "Midday Meditation, Mon-Fri",
              "teacher": "Various Teachers",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "29": {
              "id": 29,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "1:00-2:00 PM",
              "name": "Daily Reflections and Meditiation",
              "teacher": "Sharon Salzburg, others",
              "organization": "Insight Meditation Society",
              "Registration": "YouTube"
            },
            "30": {
              "id": 30,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "2:00 - 3:00 PM",
              "name": "Wisdom 2.0: Cultivating Mindfulness Daily Practice & Inquiry",
              "teacher": "Jon Kabat-Zinn",
              "organization": "Wisdom 2.0",
              "orgUrl": "http://www.wisdom2conference.com/live",
              "Registration": "Register Here",
              "Registration URL": "https://www.eventbrite.com/e/livestream-jon-kabat-zinn-cultivating-mindfulness-at-this-critical-time-tickets-101254729622?fbclid=IwAR09UWHXQAl-aNFk9kkFDwKW-OVgcu_vyMCUBAiYLABhHby1K8tf1jY_eLc"
            },
            "31": {
              "id": 31,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "3:00-3:20 PM",
              "name": "Ten Percent Happier Live - Mon-Fri",
              "teacher": "Dan Harris & Guest Teachers",
              "organization": "Ten Percent Happier",
              "Registration": "Live"
            },
            "32": {
              "id": 32,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "5:00-6:00 PM",
              "name": "Tea Time Meditation, Mon-Fri",
              "teacher": "Mary Aubry, Rob Creekmore, Amy Smith, Bill Mies, Jeff Rosenberg",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "33": {
              "id": 33,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "6:15 - 7:15 PM",
              "name": "Evening Meditation",
              "teacher": "Various",
              "organization": "Brooklyn Zen Center",
              "orgUrl": "https://brooklynzen.org/online-dharma-offerings/",
              "Registration": "Zoom",
              "Registration URL": "https://zoom.us/j/780859370"
            },
            "34": {
              "id": 34,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "1899-12-31T04:00:00.000Z",
              "name": "Evening Pujas",
              "teacher": "Various Teachers",
              "organization": "Abhayagiri",
              "Registration": "You Tube"
            },
            "35": {
              "id": 35,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "Various",
              "name": "San Francisco Zen Center",
              "teacher": "Various Teachers",
              "organization": "SF Zen Online Programs"
            },
            "36": {
              "id": 36,
              "daily": "true",
              "monday": "true",
              "tuesday": "true",
              "wednesday": "true",
              "thursday": "true",
              "friday": "true",
              "saturday": "true",
              "sunday": "true",
              "Time": "Various",
              "name": "Guided Mindful Daily",
              "teacher": "Various Teachers",
              "organization": "eMindful",
              "orgUrl": "emindful.com",
              "Registration": "Register Here",
              "Registration URL": "https://vibe.emindful.com/signup/oasis"
            },
            "37": {
              "id": 37,
              "monday": "true",
              "Time": "11:00 - 11:30 AM",
              "name": "Forest Refuge April Retreat: \nMorning Reflection & Guided Meditation",
              "teacher": "Oren Jay Sofer",
              "organization": "Oren Jay Sofer",
              "orgUrl": "https://www.orenjaysofer.com/schedule/2020/4/2-gm-live",
              "Registration": "Zoom",
              "Registration URL": "https://zoom.us/j/204024400"
            },
            "38": {
              "id": 38,
              "monday": "true",
              "Time": "11:25-12:15 PM",
              "name": "Tending the Body Through Movement and Meditation",
              "teacher": "Paloma Cain",
              "organization": "Insight L.A.",
              "Registration": "Register Here"
            },
            "39": {
              "id": 39,
              "monday": "true",
              "Time": "4:00-4:45 PM",
              "name": "Mindfully Eating Together: Addressing Emotional Consumption",
              "teacher": "Karen David",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "40": {
              "id": 40,
              "monday": "true",
              "Time": "4:00-5:00 PM",
              "name": "First Mondays",
              "teacher": "Various Teachers",
              "organization": "Gaia House U.K.",
              "Registration": "Zoom"
            },
            "41": {
              "id": 41,
              "monday": "true",
              "Time": "6:30-8:30 PM",
              "name": "Insight Dialogue Sangha - 2nd & 4th Mondays",
              "teacher": "Bart Van Melik",
              "organization": "New York Insight",
              "Registration": "Zoom"
            },
            "42": {
              "id": 42,
              "monday": "true",
              "Time": "7:00-8:00 PM",
              "name": "Monday - Denver",
              "teacher": "Kathy Hartman, Dell Brooks",
              "organization": "Insight Meditation Community of Colorado",
              "Registration": "Zoom"
            },
            "43": {
              "id": 43,
              "monday": "true",
              "Time": "7:00-8:30 PM",
              "name": "Drop-in Class",
              "teacher": "Geoff Maxson, Linda Naini, Rebecca Hines",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "44": {
              "id": 44,
              "monday": "true",
              "Time": "7:15-8:45 PM",
              "name": "Black, Indigenous, People of Color",
              "teacher": "Dawn Maurico, Muriel Jaouich",
              "organization": "True North Insight Canada",
              "Registration": "Send an email for Zoom link to d@dawnmauricio.com"
            },
            "45": {
              "id": 45,
              "monday": "true",
              "Time": "7:30-9:00 PM",
              "name": "Drop-in Class",
              "teacher": "Carole Rogetine, Alicia Bazan-Jimenez",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "46": {
              "id": 46,
              "monday": "true",
              "Time": "7:30-9:00 PM",
              "name": "Drop-in Class",
              "teacher": "Charles Agle",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "47": {
              "id": 47,
              "monday": "true",
              "Time": "7:30-9:00 PM",
              "name": "Drop-in Class",
              "teacher": "Johnathan Foust",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Facebook Live"
            },
            "48": {
              "id": 48,
              "monday": "true",
              "Time": "7:30-9:00 PM",
              "name": "Monday Night Meditation",
              "teacher": "Erin Treat, Yong Oh, others",
              "organization": "Durango Dharma Center",
              "Registration": "Zoom"
            },
            "49": {
              "id": 49,
              "monday": "true",
              "Time": "8:00-9:30 PM",
              "name": "Monday Nights",
              "teacher": "Lisa Ernst",
              "organization": "One Dharma Nashville",
              "Registration": "New Zoom Link",
              "Registration URL": "https://zoom.us/j/5522410890?pwd=NWdmVVdWeDg3cmNKSW1jelhQTmZyQT09"
            },
            "50": {
              "id": 50,
              "monday": "true",
              "Time": "8:00-9:00 PM",
              "name": "Mindfulness as Medicine: Boost Your Immune System",
              "teacher": "Lisa Kring",
              "organization": "Insight L.A.",
              "Registration": "Register Here"
            },
            "51": {
              "id": 51,
              "monday": "true",
              "Time": "8:30-9:30 PM",
              "name": "Monday Night Meditation",
              "teacher": "Rebecca Dixon",
              "organization": "Rebecca Dixon",
              "Registration": "Zoom"
            },
            "52": {
              "id": 52,
              "monday": "true",
              "Time": "8:30-9:30 PM",
              "name": "San Francisco LGBT Sangha",
              "teacher": "Various Teachers",
              "organization": "San Francisco LGBT Sangha",
              "Registration": "Zoom"
            },
            "53": {
              "id": 53,
              "monday": "true",
              "Time": "9:00-10:00 PM",
              "name": "Devon & Craig Hase Monday Sangha",
              "teacher": "Devon & Craig Hase",
              "organization": "Devon & Craig Hase",
              "Registration": "Zoom"
            },
            "54": {
              "id": 54,
              "monday": "true",
              "Time": "9:00-10:15 PM",
              "name": "Sitting and Talk",
              "teacher": "John Martin",
              "organization": "Insight Upper Market",
              "Registration": "Contact for Zoom link"
            },
            "55": {
              "id": 55,
              "monday": "true",
              "Time": "9:00-10:15 PM",
              "name": "Qigong Dharma",
              "teacher": "Teja Bell",
              "organization": "Qigong Dharma",
              "Registration": "Register Here"
            },
            "56": {
              "id": 56,
              "monday": "true",
              "Time": "9:15-10:00 PM",
              "name": "Mindful Support: What Does My Heart Need Now?",
              "teacher": "JD Lloyd",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "57": {
              "id": 57,
              "monday": "true",
              "Time": "9:30-10:30 PM",
              "name": "Modern Mindfulness",
              "teacher": "Dan Petrie",
              "organization": "SF Dharma Collective",
              "Registration": "Zoom"
            },
            "58": {
              "id": 58,
              "monday": "true",
              "Time": "9:30-10:30 PM",
              "name": "Meditación en Tiempos Difíciles",
              "teacher": "Rosamaria Segura, Tera Abdala, Mariela Bravo",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "59": {
              "id": 59,
              "monday": "true",
              "Time": "10:00-11:30 PM",
              "name": "All Community Sit",
              "teacher": "Bob Stahl",
              "organization": "Insight Santa Cruz",
              "Registration": "Zoom"
            },
            "60": {
              "id": 60,
              "monday": "true",
              "Time": "10:00PM -12:00 AM",
              "name": "Monday Dharma and Meditation",
              "teacher": "Tuere Sala, Time Geil",
              "organization": "Seattle Insight",
              "Registration": "Zoom"
            },
            "61": {
              "id": 61,
              "monday": "true",
              "Time": "10:00PM-12:00 AM",
              "name": "Monday Meeting",
              "teacher": "Brian Lesage",
              "organization": "Flagstaff Insight",
              "Registration": "Zoom"
            },
            "62": {
              "id": 62,
              "monday": "true",
              "Time": "10:15PM-12:15 AM",
              "name": "Monday Night",
              "teacher": "Jack Kornfield and others",
              "organization": "Spirit Rock",
              "Registration": "Monday Night"
            },
            "63": {
              "id": 63,
              "monday": "true",
              "Time": "10:30PM-12:00 AM",
              "name": "Sitting and Talk",
              "teacher": "Gil Fronsdal",
              "organization": "Insight Meditation Center",
              "Registration": "YouTube"
            },
            "64": {
              "id": 64,
              "monday": "true",
              "Time": "10:30PM-12:00 AM",
              "name": "Women's Group",
              "teacher": "Juliana Sloane",
              "organization": "SF Insight",
              "Registration": "Zoom (Password 229216)",
              "Registration URL": "https://zoom.us/j/4526958576?pwd=cE9VRkRUbjFIK3JxRnp0eG8ySWFvZz09"
            },
            "65": {
              "id": 65,
              "monday": "true",
              "Time": "10:30PM-1:00 AM",
              "name": "Good Night Meditation: Relax and Sleep Well",
              "teacher": "Beth Sternlieb",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "66": {
              "id": 66,
              "monday": "true",
              "Time": "11:00PM-12:30 AM",
              "name": "Bay Area Pragmatic Dharma Sangha",
              "teacher": "Tucker Peck",
              "organization": "SF Dharma Collective",
              "Registration": "Zoom"
            },
            "67": {
              "id": 67,
              "tuesday": "true",
              "Time": "9:00-9:30 AM",
              "name": "Weekly Sitting Group",
              "teacher": "Daryl Lynn Ross",
              "organization": "True North Insight Canada",
              "Registration": "YouTube"
            },
            "68": {
              "id": 68,
              "tuesday": "true",
              "Time": "11:00AM - 1:00 PM",
              "name": "Path of Joy Sangha, Costa Rica",
              "teacher": "Barbara Moss",
              "organization": "Path of Joy Sangha",
              "orgUrl": "https://www.facebook.com/Path-of-Joy-Sangha-108740063905610/",
              "Registration": "Email to Join",
              "Registration URL": "mailto:barbsmss@gmail.com"
            },
            "69": {
              "id": 69,
              "tuesday": "true",
              "Time": "11:00 - 11:30 AM",
              "name": "Forest Refuge April Retreat: \nDharma Talk",
              "teacher": "Oren Jay Sofer",
              "organization": "Oren Jay Sofer",
              "orgUrl": "https://www.orenjaysofer.com/schedule/2020/4/2-gm-live",
              "Registration": "Zoom",
              "Registration URL": "https://zoom.us/j/204024400"
            },
            "70": {
              "id": 70,
              "tuesday": "true",
              "Time": "11:00-12:00 PM",
              "name": "Opening Your Heart to the World with Mindful Astoria",
              "teacher": "Kimberly Brown",
              "organization": "Mindful Astoria",
              "Registration": "Zoom",
              "Registration URL": "https://www.meetup.com/Mindful-Astoria/events/fjwxqrybcgbsb/"
            },
            "71": {
              "id": 71,
              "tuesday": "true",
              "Time": "12:00-12:30 PM",
              "name": "Weekly Sitting Group",
              "teacher": "Jill Davey",
              "organization": "True North Insight Canada",
              "Registration": "Zoom"
            },
            "72": {
              "id": 72,
              "tuesday": "true",
              "Time": "1:00-2:30 PM",
              "name": "Aging as a Spiritual Practice",
              "teacher": "Various Teachers",
              "organization": "New York Insight",
              "Registration": "Zoom"
            },
            "73": {
              "id": 73,
              "tuesday": "true",
              "Time": "5:30-6:30 PM",
              "name": "The Boundless Heart: Metta and Compassion for All",
              "teacher": "Celeste Young",
              "organization": "Insight L.A.",
              "Registration": "Register Here"
            },
            "74": {
              "id": 74,
              "tuesday": "true",
              "Time": "6:30-8:00 PM",
              "name": "Drop-in Class",
              "teacher": "Rebecca Hines",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "75": {
              "id": 75,
              "tuesday": "true",
              "Time": "7:00-9:00 PM",
              "name": "Tuesday Dharma Gathering",
              "teacher": "Various Teachers:\n3/31: Bart Van Melik",
              "organization": "New York Insight",
              "Registration": "Zoom"
            },
            "76": {
              "id": 76,
              "tuesday": "true",
              "Time": "7:00-8:30 PM",
              "name": "Drop-in Class",
              "teacher": "Trish Magyari, Stan Eisenstein, Mira Tessman",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "77": {
              "id": 77,
              "tuesday": "true",
              "Time": "7:00-8:00 PM",
              "name": "Drop-in Class",
              "teacher": "Hugh Byrne",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "78": {
              "id": 78,
              "tuesday": "true",
              "Time": "7:00-8:30 PM",
              "name": "Tuesday Evening Practice Group",
              "teacher": "Various Teachers",
              "organization": "Frederick Meditation Center",
              "Registration": "Zoom"
            },
            "79": {
              "id": 79,
              "tuesday": "true",
              "Time": "7:00-8:30 PM",
              "name": "Brooklyn Sangha",
              "teacher": "Various Teachers",
              "organization": "New York Insight",
              "Registration": "Zoom"
            },
            "80": {
              "id": 80,
              "tuesday": "true",
              "Time": "7:30-9:00 PM",
              "name": "Drop-in Class",
              "teacher": "Steve Zappalla",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "81": {
              "id": 81,
              "tuesday": "true",
              "Time": "8:00-9:15 PM",
              "name": "Relational Practices: Finding Refuge in Community Together",
              "teacher": "Lisa Kring",
              "organization": "Insight L.A.",
              "Registration": "Register Here"
            },
            "82": {
              "id": 82,
              "tuesday": "true",
              "Time": "8:00-10:00 PM",
              "name": "Tuesday - Boulder",
              "teacher": "David Chernikoff",
              "organization": "Insight Meditation Community of Colorado",
              "Registration": "Zoom"
            },
            "83": {
              "id": 83,
              "tuesday": "true",
              "Time": "6:00-7:30 PM",
              "name": "Weekly Class",
              "teacher": "T Maes, Devon Cresci",
              "organization": "Anthony Maes",
              "orgUrl": "http://www.anthonymaes.com/classes",
              "Registration": "Zoom",
              "Registration URL": "https://zoom.us/j/955240986"
            },
            "84": {
              "id": 84,
              "tuesday": "true",
              "Time": "9:00-9:45 PM",
              "name": "Community Sit for the World and Ourselves",
              "teacher": "Ava Louise Stanton, Wendy Schmelzer",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "85": {
              "id": 85,
              "tuesday": "true",
              "Time": "9:15-10:00 PM",
              "name": "Stillness in a Chaotic World: Surfing the Waves of Experience",
              "teacher": "James Rosser",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "86": {
              "id": 86,
              "tuesday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Alphabet Sangha",
              "teacher": "Various Teachers",
              "organization": "East Bay Meditation Center",
              "Registration": "Please email alphabetsangha@eastbaymeditation.org to request Zoom link"
            },
            "87": {
              "id": 87,
              "tuesday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Reflections",
              "teacher": "Jessica Swanson",
              "organization": "Portland Friends of the Dhamma",
              "Registration": "Coming Soon"
            },
            "88": {
              "id": 88,
              "tuesday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Boundless Heart Livestream",
              "teacher": "Gary Sanders",
              "organization": "Portland Insight",
              "Registration": "Zoom"
            },
            "89": {
              "id": 89,
              "tuesday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Tuesday Night",
              "teacher": "Howie Cohn",
              "organization": "Mission Dharma",
              "Registration": "Zoom"
            },
            "90": {
              "id": 90,
              "tuesday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Tuesday Night Sit",
              "teacher": "Various",
              "organization": "Insight Santa Cruz",
              "Registration": "Zoom"
            },
            "91": {
              "id": 91,
              "tuesday": "true",
              "Time": "10:00-12:00 AM",
              "name": "Dharma en Espanol",
              "teacher": "Andrea Castillo",
              "organization": "Insight Meditation Center",
              "Registration": "Zoom"
            },
            "92": {
              "id": 92,
              "tuesday": "true",
              "Time": "10:15-12:00 AM",
              "name": "Insight Meditation Satsang",
              "teacher": "Sean Feit Oakes",
              "organization": "Ashtanga Yoga Berkeley",
              "Registration": "Facebook"
            },
            "93": {
              "id": 93,
              "tuesday": "true",
              "Time": "10:30-11:30 PM",
              "name": "Sitting, Questions and Reflections",
              "teacher": "Andrea Fella",
              "organization": "Insight Meditation Center",
              "Registration": "Zoom"
            },
            "94": {
              "id": 94,
              "tuesday": "true",
              "Time": "10:30-12:15 AM",
              "name": "Community Practice Group",
              "teacher": "Maureen Shannon-Chapple",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "95": {
              "id": 95,
              "tuesday": "true",
              "Time": "10:30-12:15 AM",
              "name": "South Bay - Redondo Beach Practice Group",
              "teacher": "Eric McCullum, Alit Hedayat",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "96": {
              "id": 96,
              "wednesday": "true",
              "Time": "10:00-11:45 AM",
              "name": "Wednesday Wake-Up Livestrem",
              "teacher": "Gergory Maloof",
              "organization": "Portland Insight",
              "Registration": "Zoom"
            },
            "97": {
              "id": 97,
              "wednesday": "true",
              "Time": "12:00-1:30 PM",
              "name": "Sacred Movement",
              "teacher": "Karen Cryer",
              "organization": "Insight L.A.",
              "Registration": "Register Here"
            },
            "98": {
              "id": 98,
              "wednesday": "true",
              "Time": "12:00-12:45 PM",
              "name": "Meditación en Español Calmando la Mente y el Corazón",
              "teacher": "Rosmaria Segura, Tere Abdala",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "99": {
              "id": 99,
              "wednesday": "true",
              "Time": "12:00-12:30 PM",
              "name": "Weekly Sitting Group",
              "teacher": "Muriel Jaouich",
              "organization": "True North Insight Canada",
              "Registration": "YouTube"
            },
            "100": {
              "id": 100,
              "wednesday": "true",
              "Time": "1:00PM-3:00PM",
              "name": "Wednesday Morning Meditation",
              "teacher": "Sylvia Boorstein, Donald Rothberg",
              "organization": "Spirit Rock",
              "Registration": "Register Here"
            },
            "101": {
              "id": 101,
              "wednesday": "true",
              "Time": "1:15PM-2:45 PM",
              "name": "Mindful Aging: Supporting Each Other Through the Season of the Coranavirus",
              "teacher": "Wendy Schmelzer",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "102": {
              "id": 102,
              "wednesday": "true",
              "Time": "2:00PM-3:00PM",
              "name": "Virtual Sangha el Mierocoles - en Espanol",
              "teacher": "Various Teachers",
              "organization": "Dhamma Madrid",
              "Registration": "Zoom"
            },
            "103": {
              "id": 103,
              "wednesday": "true",
              "Time": "2:00PM-3:00PM",
              "name": "Sitting and Talk",
              "teacher": "Gil Fronsdal",
              "organization": "Insight Meditation Center",
              "Registration": "YouTube"
            },
            "104": {
              "id": 104,
              "wednesday": "true",
              "Time": "3:00-3:45 PM",
              "name": "Compassion and Resilience - Guided Mediation for Difficult Times",
              "teacher": "Angelike Dexter",
              "organization": "Insight L.A.",
              "Registration": "Register Here"
            },
            "105": {
              "id": 105,
              "wednesday": "true",
              "Time": "5:00-6:30 PM",
              "name": "Finding Sanctuary in Times of Chaos",
              "teacher": "Amma Thanasanti",
              "organization": "Awakening Truth",
              "Registration": "Register Here"
            },
            "106": {
              "id": 106,
              "wednesday": "true",
              "Time": "5:00-7:00 PM",
              "name": "Queer Sangha",
              "teacher": "Pierre-Vincent Breault- Ruel, Coral Short",
              "organization": "True North Insight Canada",
              "Registration": "Zoom"
            },
            "107": {
              "id": 107,
              "wednesday": "true",
              "Time": "5:30-6:00 PM",
              "name": "Teen Mindfulness Group",
              "teacher": "Travis Spencer",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "108": {
              "id": 108,
              "wednesday": "true",
              "Time": "6:30-7:30 PM",
              "name": "Community Meditation Center of New York \nWednesday Evening Session",
              "teacher": "Rachel Hammerman (4/8), Vera Ruantragool, Lauren Cohen",
              "organization": "CMC New York",
              "orgUrl": "https://cmcnewyork.org/",
              "Registration": "Zoom"
            },
            "109": {
              "id": 109,
              "wednesday": "true",
              "Time": "7:30-9:30 PM",
              "name": "Northside Sangha Sitting",
              "teacher": "Various Teachers",
              "organization": "Insight Chicago Meditation Community",
              "orgUrl": "https://www.insightchicago.org/northside-meditation-sangha",
              "Registration": "Go Here for Zoom Link",
              "Registration URL": "https://www.insightchicago.org/meditation-locations"
            },
            "110": {
              "id": 110,
              "wednesday": "true",
              "Time": "7:00-8:30 PM",
              "name": "Drop-in Class",
              "teacher": "Stan Eisenstein",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "111": {
              "id": 111,
              "wednesday": "true",
              "Time": "7:30-9:30 PM",
              "name": "Sutra Service and Meditation Practice",
              "teacher": "Rev. Jay Rinsen Weik Roshi, Rev. Karen Do'on Weik Osho",
              "organization": "Buddhist Temple of Toledo",
              "Registration": "Livestream on Facebook"
            },
            "112": {
              "id": 112,
              "wednesday": "true",
              "Time": "7:30-9:30 PM",
              "name": "Wednesday - Boulder",
              "teacher": "Peter Williams",
              "organization": "Insight Meditation Community of Colorado",
              "Registration": "To Register Contact Peter"
            },
            "113": {
              "id": 113,
              "wednesday": "true",
              "Time": "7:30-8:30 PM",
              "name": "Weekly Sitting Group",
              "teacher": "Jill Davey",
              "organization": "True North Insight Canada",
              "Registration": "YouTube"
            },
            "114": {
              "id": 114,
              "wednesday": "true",
              "Time": "7:30-8:45 PM",
              "name": "Harlem Insight",
              "teacher": "Various Teachers",
              "organization": "New York Insight",
              "Registration": "Zoom"
            },
            "115": {
              "id": 115,
              "wednesday": "true",
              "Time": "7:30-9:00 PM",
              "name": "Wednesdays with Tara",
              "teacher": "Tara Brach",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Facebook"
            },
            "116": {
              "id": 116,
              "wednesday": "true",
              "Time": "7:30-9:00 PM",
              "name": "Drop-in Class",
              "teacher": "Laura Dorsett",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "117": {
              "id": 117,
              "wednesday": "true",
              "Time": "8:00 - 9:00 PM",
              "name": "Virtual Guided Meditation",
              "teacher": "Lama Surya Das",
              "organization": "Dzogchen Center",
              "orgUrl": "https://dzogchen.org/",
              "Registration": "Zoom",
              "Registration URL": "http://r20.rs6.net/tn.jsp?f=001lDzMNS5x-bqxVDa2GAjxorWSro2HGR3MhLuRHxxZ3lrj9AbeOyoTvYM9IwHvmpn8UXyg6AsSyg6nQE-JOArmtnaOtWgvJM964SZg7aPcAi6ZegQOH91UtJEkDph5GSJIq_ZNacKY2xBdNKaRiC7qBCgcJXvdBgqp9tKNOgE-ZYGlMW5Lcn6j6K7lVFjLHd_KizdPfkVKekQCRGK8TDPYBFca1cq7xRTFzDhGx6eKnxZEl8TYOvVVWC0e3BpXqWUOVED3kBo1KYc4oAJQTqPUVmdGn7Eb3NPcKYlDaxdrX43fCiSSBEwKCkAGg07ajzfpdj45XXpPYMZv46W8pG0Sn0NQoYz3M6zH2aElyCi4mgObnYir4V_uMQqo5h5fATYY11J9dDqjFok=&c=M46-FGM-f6UoERpMBaaRF_jIqaieojD1H3Ky9uMCyWXYaBTsmZotsA==&ch=cxSI6HAB8CxYmN98mRJJO5liBD7XYrnx65nRz0Sdj3FRkWxNZrVDTA=="
            },
            "118": {
              "id": 118,
              "wednesday": "true",
              "Time": "8:30-10:00 PM",
              "name": "Weekly Practice Group",
              "teacher": "Shelly Graf",
              "organization": "Common Ground",
              "Registration": "You Tube"
            },
            "119": {
              "id": 119,
              "wednesday": "true",
              "Time": "9:00-10:00 PM",
              "name": "Drop In Dharma",
              "teacher": "Pamela Weiss and others",
              "organization": "SF Insight",
              "Registration": "Zoom"
            },
            "120": {
              "id": 120,
              "wednesday": "true",
              "Time": "9:00-10:00 PM",
              "name": "Happy Hour: Practicing Loving-Kindness",
              "teacher": "Diana Clark, Nikki Mirghafori",
              "organization": "Insight Meditation Center",
              "Registration": "IMC"
            },
            "121": {
              "id": 121,
              "wednesday": "true",
              "Time": "9:00-10:15 PM",
              "name": "Saskatoon Insight Meditation Community",
              "teacher": "Jeanne Corrigal",
              "organization": "Saskatoon Insight Meditation Community",
              "orgUrl": "https://saskatooninsight.com/wp/",
              "Registration": "Zoom",
              "Registration URL": "https://zoom.us/j/111133036"
            },
            "122": {
              "id": 122,
              "wednesday": "true",
              "Time": "9:00-10:30 PM",
              "name": "Meditation Group",
              "teacher": "Rick Hanson",
              "organization": "Rick Hanson",
              "Registration": "Zoom"
            },
            "123": {
              "id": 123,
              "wednesday": "true",
              "Time": "9:15-10:00 PM",
              "name": "Be With the Body 0 Guided Meditation",
              "teacher": "Chris Spurell",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "124": {
              "id": 124,
              "wednesday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Meditation with Dharma Talk and Discussion",
              "teacher": "Rachel Lewis",
              "organization": "British Columbia Insight Meditation Society",
              "Registration": "Zoom"
            },
            "125": {
              "id": 125,
              "wednesday": "true",
              "Time": "10:00-11:00 PM",
              "name": "Mindfulness for Healthcare Professionals: Caring for Ourselves While Caring for Others",
              "teacher": "Suzanne Smith",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "126": {
              "id": 126,
              "wednesday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Dharma Homies Santa Cruz",
              "teacher": "Jessica Escobedo, Joe Clements",
              "Registration": "New Zoom Link",
              "Registration URL": "https://zoom.us/j/274238721"
            },
            "127": {
              "id": 127,
              "wednesday": "true",
              "Time": "10:00-11:45 PM",
              "name": "Teen Circle",
              "teacher": "Various Teachers",
              "organization": "East Bay Meditation Center",
              "Registration": "Register Here"
            },
            "128": {
              "id": 128,
              "wednesday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Metta Dharma Foundation",
              "teacher": "Richard Shankman",
              "organization": "Metta Dharma",
              "Registration": "Zoom"
            },
            "129": {
              "id": 129,
              "wednesday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Under Forty Group, 2nd & 4th Wednesdays",
              "teacher": "Keri Pederson",
              "organization": "Seattle Insight",
              "Registration": "Zoom"
            },
            "130": {
              "id": 130,
              "wednesday": "true",
              "Time": "10:00PM-12:00 AM",
              "name": "Chanting, Meditation, Dhamma, Sutta Study",
              "teacher": "Ayya Santussika",
              "organization": "Karuna Buddhist Vihara",
              "Registration": "Uber Conference"
            },
            "131": {
              "id": 131,
              "wednesday": "true",
              "Time": "10:30PM-12:00 AM",
              "name": "Well of Being",
              "teacher": "Eve Eckman, Chandra Easton",
              "organization": "SF Dharma Collective",
              "Registration": "Zoom"
            },
            "132": {
              "id": 132,
              "wednesday": "true",
              "Time": "10:30PM-12:00 AM",
              "name": "Dharma Study Group",
              "teacher": "Michael Zittel",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "133": {
              "id": 133,
              "thursday": "true",
              "Time": "11:00 - 12:00 PM",
              "name": "Forest Refuge April Retreat: \nOpen Q&A",
              "teacher": "Oren Jay Sofer",
              "organization": "Oren Jay Sofer",
              "orgUrl": "https://www.orenjaysofer.com/schedule/2020/4/2-gm-live",
              "Registration": "Zoom",
              "Registration URL": "https://zoom.us/j/204024400"
            },
            "134": {
              "id": 134,
              "thursday": "true",
              "Time": "1:00PM-3:00PM",
              "name": "Thursday Morning Women's Group",
              "teacher": "Grace Fisher",
              "organization": "Spirit Rock",
              "Registration": "Register Here"
            },
            "135": {
              "id": 135,
              "thursday": "true",
              "Time": "2:00PM-3:00PM",
              "name": "Virtual Sangha el Jeueves - en Espanol",
              "teacher": "Various Teachers",
              "organization": "Dhamma Madrid",
              "Registration": "Zoom"
            },
            "136": {
              "id": 136,
              "thursday": "true",
              "Time": "2:00PM-4:00PM",
              "name": "Senior Sangha Group, 4th Thursdays",
              "teacher": "David Cohn, Fiona Barner, Robert Cusick",
              "organization": "Insight Meditation Center",
              "Registration": "Zoom"
            },
            "137": {
              "id": 137,
              "thursday": "true",
              "Time": "2:30PM-4:00PM",
              "name": "Meditation Practice Reflections and Q&A",
              "teacher": "Gil Fronsdal",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "138": {
              "id": 138,
              "thursday": "true",
              "Time": "3:00-4:00 PM",
              "name": "Virtual Sangha",
              "teacher": "Jim Forbes, Ana Monica",
              "organization": "Dhamma Madrid",
              "Registration": "Zoom"
            },
            "139": {
              "id": 139,
              "thursday": "true",
              "Time": "3:30-5:30 PM",
              "name": "Support Group for Persons with Life Threatening Illnesses and Chronic Health Challenges, 1st & 3rd Sundays",
              "teacher": "Ying Chen",
              "organization": "Insight Meditation Center",
              "Registration": "See the events calendar for how to join this group"
            },
            "140": {
              "id": 140,
              "thursday": "true",
              "Time": "4:00-5:15 PM",
              "name": "Relational Practices: Conflict & Connection in High Intensity Times",
              "teacher": "Justine Dawson",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "141": {
              "id": 141,
              "thursday": "true",
              "Time": "6:30-8:00 PM",
              "name": "Evanston Sangha",
              "teacher": "Various Teachers",
              "organization": "Insight Chicago Meditation Community",
              "orgUrl": "https://www.insightchicago.org/evanston-meditation-sangha",
              "Registration": "Zoom"
            },
            "142": {
              "id": 142,
              "thursday": "true",
              "Time": "7:45-8:45 PM",
              "name": "Heart Refuge Mindfulness Community DC",
              "teacher": "Ayesha Ali, Rashid Hughes",
              "organization": "Heart Refuge DC",
              "Registration": "Register Here"
            },
            "143": {
              "id": 143,
              "thursday": "true",
              "Time": "7:00-8:00 PM",
              "name": "Weekly Sitting Group",
              "teacher": "Steven Hick",
              "organization": "True North Insight Canada",
              "Registration": "Zoom"
            },
            "144": {
              "id": 144,
              "thursday": "true",
              "Time": "7:00-8:30 PM",
              "name": "Discovering (Self)Compassion",
              "teacher": "Kimberly Brown",
              "organization": "Shantideva Center",
              "orgUrl": "https://shantidevanyc.org/programs/meditation/metta-meditation/",
              "Registration": "Register for Zoom Link",
              "Registration URL": "https://shantidevanyc.org/programs/meditation/metta-meditation/"
            },
            "145": {
              "id": 145,
              "thursday": "true",
              "Time": "7:15-8:45 PM",
              "name": "Weekly Meditation",
              "teacher": "Chris Crotty",
              "organization": "Boston Meditation Center",
              "Registration": "Zoom"
            },
            "146": {
              "id": 146,
              "thursday": "true",
              "Time": "7:30-9:00 PM",
              "name": "Drop-in Class",
              "teacher": "Mary Vandavanter",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "147": {
              "id": 147,
              "thursday": "true",
              "Time": "8:00-9:00 PM",
              "name": "Guided Meditation and Teaching: Staying Well Nourished in these Times",
              "teacher": "Andrea Lieberstein",
              "organization": "Andrea Lieberstein",
              "orgUrl": "www.yourwellnourishedlife.com",
              "Registration": "Register Here",
              "Registration URL": "https://www.eventbrite.com/e/staying-well-nourished-in-these-times-weekly-meditation-sessions-tickets-101592961282  "
            },
            "148": {
              "id": 148,
              "thursday": "true",
              "Time": "8:30-10:00 PM",
              "name": "Kindness Lab",
              "teacher": "Todd Jordan",
              "organization": "SF Dharma Collective",
              "Registration": "Zoom"
            },
            "149": {
              "id": 149,
              "thursday": "true",
              "Time": "9:00-11:00 PM",
              "name": "Thursday Meeting",
              "teacher": "Brian Lesage",
              "organization": "Flagstaff Insight",
              "Registration": "Zoom"
            },
            "150": {
              "id": 150,
              "thursday": "true",
              "Time": "9:30-11:30 PM",
              "name": "Capitol Hill Meditation Group",
              "teacher": "Tuere Sala",
              "organization": "Capital Hill Meditation Group",
              "Registration": "Zoom"
            },
            "151": {
              "id": 151,
              "thursday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Thursday Sit and Dharma Talk",
              "teacher": "Mary Stancavage",
              "organization": "Undefended Dharma",
              "Registration": "Zoom"
            },
            "152": {
              "id": 152,
              "thursday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Sit and Dharma Talk",
              "teacher": "Dennis Warren",
              "organization": "Sacramento Insight Meditation",
              "Registration": "Zoom"
            },
            "153": {
              "id": 153,
              "thursday": "true",
              "Time": "10:00-11:15 PM",
              "name": "Thursday Night Metta",
              "teacher": "Kirsten Rudestam, Marcy Reynolds",
              "organization": "Insight Santa Cruz",
              "Registration": "Zoom"
            },
            "154": {
              "id": 154,
              "thursday": "true",
              "Time": "10:00PM-12:00 AM",
              "name": "People of Color Sangha",
              "teacher": "Various",
              "organization": "East Bay Meditation Center",
              "Registration": "Sign Up Here"
            },
            "155": {
              "id": 155,
              "thursday": "true",
              "Time": "10:00-12:00 AM",
              "name": "Eastside Meditation Group, 1st & 3rd Thursdays",
              "teacher": "Steve Wilhelm",
              "organization": "Seattle Insight",
              "Registration": "Zoom"
            },
            "156": {
              "id": 156,
              "thursday": "true",
              "Time": "10:30-12:15 AM",
              "name": "Heart of Freedom Livestream",
              "teacher": "Doug Pullin",
              "organization": "Portland Insight",
              "Registration": "Zoom"
            },
            "157": {
              "id": 157,
              "thursday": "true",
              "Time": "10:30-12:30 AM",
              "name": "Weekly Meeting",
              "teacher": "James Baraz",
              "organization": "Insight Meditation Community of Berkeley",
              "Registration": "Zoom"
            },
            "158": {
              "id": 158,
              "thursday": "true",
              "Time": "10:30-12:15 AM",
              "name": "Thursday Evening Practice Group",
              "teacher": "Diana Gould",
              "organization": "Insight L.A.",
              "Registration": "Register Here"
            },
            "159": {
              "id": 159,
              "thursday": "true",
              "Time": "10:30PM-12:00 AM",
              "name": "Deconstructing Yourself",
              "teacher": "Michael Taft",
              "organization": "SF Dharma Collective",
              "Registration": "YouTube"
            },
            "160": {
              "id": 160,
              "thursday": "true",
              "Time": "10:30PM-12:00 AM",
              "name": "Virtual Dharma Talk",
              "teacher": "George Haas",
              "organization": "The Metta Group",
              "orgUrl": "https://www.mettagroup.org/",
              "Registration": "Zoom",
              "Registration URL": "https://zoom.us/j/7316702955"
            },
            "161": {
              "id": 161,
              "friday": "true",
              "Time": "12:15-1:00 PM",
              "name": "Shift from Doing into Being - Guided Meditation",
              "teacher": "Megan Heiser",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "162": {
              "id": 162,
              "friday": "true",
              "Time": "1:00PM-3:00 PM",
              "name": "Dharma and Recovery, 2nd Fridays",
              "teacher": "Kevin Griffin",
              "organization": "Spirit Rock",
              "orgUrl": "https://www.spiritrock.org/",
              "Registration": "Zoom",
              "Registration URL": "https://zoom.us/j/621325075"
            },
            "163": {
              "id": 163,
              "friday": "true",
              "Time": "3:00-3:45 PM",
              "name": "Calm the Mind - Guided Meditation",
              "teacher": "Izumi Tanaka",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "164": {
              "id": 164,
              "friday": "true",
              "Time": "4:00-5:00 PM",
              "name": "Mindful Parents Practice Group",
              "teacher": "Angelike Dexter",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "165": {
              "id": 165,
              "friday": "true",
              "Time": "4:00-5:15 PM",
              "name": "Relational Practices: All of You Is Welcome Here",
              "teacher": "Lisette Palley",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "166": {
              "id": 166,
              "friday": "true",
              "Time": "5:00-6:00 PM",
              "name": "Puerto Rico - Los Angeles Uniendo Corazones",
              "teacher": "Rosmaria Segura, Delia Roman",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "167": {
              "id": 167,
              "friday": "true",
              "Time": "5:00-6:30PM",
              "name": "Finding Sanctuary in Times of Chaos",
              "teacher": "Amma Thanasanti",
              "organization": "Awakening Truth",
              "Registration": "Register Here"
            },
            "168": {
              "id": 168,
              "friday": "true",
              "Time": "5:30-6:15PM",
              "name": "Petitation: Practicing Mediation with Our Pets",
              "teacher": "Various Teachers",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "169": {
              "id": 169,
              "friday": "true",
              "Time": "6:00-7:00 PM",
              "name": "Center for Compassion and Mindfulness POC Group",
              "teacher": "Rahil Rojiani",
              "organization": "Center for Mindfulness and Compassion",
              "Registration": "Zoom"
            },
            "170": {
              "id": 170,
              "friday": "true",
              "Time": "6:15-8:00 PM",
              "name": "Virus Thinking: The Gift of Fear",
              "teacher": "Josyln Hitter",
              "organization": "Insight L.A.",
              "Registration": "Register Here"
            },
            "171": {
              "id": 171,
              "friday": "true",
              "Time": "7:00-8:15 PM",
              "name": "Friday Evening Practice Group: Heart Practice Meditation",
              "teacher": "Ray Manyoky",
              "organization": "Frederick Meditation Center",
              "Registration": "Zoom"
            },
            "172": {
              "id": 172,
              "friday": "true",
              "Time": "8:00-9:00 PM",
              "name": "Online Weekly Sitting",
              "teacher": "Various Teachers",
              "organization": "True North Insight Canada",
              "Registration": "YouTube"
            },
            "173": {
              "id": 173,
              "friday": "true",
              "Time": "8:00-9:00 PM",
              "name": "Weekly Sitting Group",
              "teacher": "Daryl Lynn Ross",
              "organization": "True North Insight Canada",
              "Registration": "YouTube"
            },
            "174": {
              "id": 174,
              "friday": "true",
              "Time": "8:00-9:15 PM",
              "name": "Managing Challenging Emotuons in Uncertainty",
              "teacher": "Lisa Kring",
              "organization": "Insight L.A.",
              "Registration": "Register Here"
            },
            "175": {
              "id": 175,
              "friday": "true",
              "Time": "9:00-10:00 PM",
              "name": "Recovery Dharma Friday Group",
              "teacher": "Peer Led",
              "organization": "SF Dharma Collective",
              "Registration": "Zoom"
            },
            "176": {
              "id": 176,
              "friday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Mindful Recovery",
              "teacher": "Michael Torres",
              "organization": "Mindful Recovery Tumblr Web Site",
              "Registration": "Zoom"
            },
            "177": {
              "id": 177,
              "friday": "true",
              "Time": "10:00-12:00 AM",
              "name": "Friday Night Investigators",
              "teacher": "Matthew Grad",
              "organization": "Portland Friends of the Dhamma",
              "Registration": "Zoom"
            },
            "178": {
              "id": 178,
              "friday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Maha Sangha",
              "teacher": "Various Teachers",
              "organization": "East Bay Meditation Center",
              "Registration": "Zoom"
            },
            "179": {
              "id": 179,
              "friday": "true",
              "Time": "10:00-12:00 AM",
              "name": "People of Color Sangha Practice Grooup",
              "teacher": "Various Teachers",
              "organization": "Insight L.A.",
              "Registration": "Register Here"
            },
            "180": {
              "id": 180,
              "friday": "true",
              "Time": "10:15-12:15 AM",
              "name": "Mindful Recovery, 3rd Fridays",
              "teacher": "Various Teachers",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "181": {
              "id": 181,
              "friday": "true",
              "Time": "10:30-12:00 AM",
              "name": "SF Weekly Group",
              "teacher": "Vinny Ferraro",
              "organization": "Big Heart City Meditation",
              "Registration": "Zoom"
            },
            "182": {
              "id": 182,
              "saturday": "true",
              "Time": "9:00-10:00 AM",
              "name": "Weekly Sitting Group",
              "teacher": "Jill Davey",
              "organization": "True North Insight Canada",
              "Registration": "Zoom"
            },
            "183": {
              "id": 183,
              "saturday": "true",
              "Time": "9:00-10:30 AM",
              "name": "Military Veterans Sangha",
              "teacher": "Steve Zappalla",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "184": {
              "id": 184,
              "saturday": "true",
              "Time": "10:00-11:00 AM",
              "name": "Women's Group",
              "teacher": "Rashmi Nair-Ripley",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "185": {
              "id": 185,
              "saturday": "true",
              "Time": "11:00AM-12:00 PM",
              "name": "Deep South Dharma Oxford Practice Group",
              "teacher": "Acharya Christie Bates, Jaya Judy Seeley",
              "organization": "Deep South Dharma",
              "Registration": "Zoom"
            },
            "186": {
              "id": 186,
              "saturday": "true",
              "Time": "12:00PM-1:00 PM",
              "name": "Guided Mediation and Q&A",
              "teacher": "Anushka Fernandopulle",
              "organization": "Anushka",
              "Registration": "Instagram Live"
            },
            "187": {
              "id": 187,
              "saturday": "true",
              "Time": "1:00PM-3:00PM",
              "name": "How do we apply the Dhamma to This?",
              "teacher": "Ayya Santussika",
              "organization": "Karuna Buddhist Vihara",
              "Registration": "Uber Conference"
            },
            "188": {
              "id": 188,
              "saturday": "true",
              "Time": "4:00-6:00 PM",
              "name": "San Franciso Zen Center Queer Dharma Group, 2nd Saturdays",
              "teacher": "Various Teachers",
              "organization": "San Francisco Zen Center Queer Dharma Group",
              "Registration": "Check here for Link"
            },
            "189": {
              "id": 189,
              "saturday": "true",
              "Time": "4:00-6:30 PM",
              "name": "People of Color Sangha - 4th Saturdays",
              "teacher": "La Sarmiento and Guest Teachers",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "190": {
              "id": 190,
              "saturday": "true",
              "Time": "8:30-10:00 PM",
              "name": "Q Sangha - 4th Saturdays",
              "teacher": "Various Teachers",
              "organization": "SF Dharma Collective",
              "Registration": "Zoom"
            },
            "191": {
              "id": 191,
              "saturday": "true",
              "Time": "9:00-11:00 PM",
              "name": "Psychedelic Sangha, 1st Saturdays",
              "teacher": "Erik Davis",
              "organization": "Psychedelic Sangha",
              "Registration": "Zoom"
            },
            "192": {
              "id": 192,
              "sunday": "true",
              "Time": "9:00-10:00 AM",
              "name": "Drop-in Class",
              "teacher": "Trisha Stotler, Jon Waterman, Jeff Rosenberg",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "193": {
              "id": 193,
              "sunday": "true",
              "Time": "9:15-10:00 AM",
              "name": "Drop-in Class",
              "teacher": "Steve Zappalla",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "194": {
              "id": 194,
              "sunday": "true",
              "Time": "9:30-10:30 AM",
              "name": "Sunday Meditation and Dharma",
              "teacher": "Terry Ray",
              "organization": "Insight Meditation Community of Colorado",
              "Registration": "Zoom"
            },
            "195": {
              "id": 195,
              "sunday": "true",
              "Time": "9:30-10:30 AM",
              "name": "Drop-in Class",
              "teacher": "Adam Silcott",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "196": {
              "id": 196,
              "sunday": "true",
              "Time": "10:00-11:00 AM",
              "name": "Opening Your Heart to the World with Mindful Astoria",
              "teacher": "Kimberly Brown",
              "organization": "Mindful Astoria",
              "Registration": "Zoom",
              "Registration URL": "https://www.meetup.com/Mindful-Astoria/events/nvlhrrybcgbqb/"
            },
            "197": {
              "id": 197,
              "sunday": "true",
              "Time": "10:30-11:30 AM",
              "name": "Drop-in Class",
              "teacher": "Hugh Byrne",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "198": {
              "id": 198,
              "sunday": "true",
              "Time": "10:30AM-12:00 PM",
              "name": "Community Meditation Center of New York\nSunday Morning Session",
              "teacher": "Allan Lokos & Various: \nJoseph Goldstein 4/7",
              "organization": "CMC New York",
              "orgUrl": "https://cmcnewyork.org/",
              "Registration": "Zoom Link Here",
              "Registration URL": "https://cmcnewyork.org/calendar/"
            },
            "199": {
              "id": 199,
              "sunday": "true",
              "Time": "10:30AM-12:00 PM",
              "name": "Sunday Morning Meditation Group",
              "teacher": "Hugh Byrne",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "200": {
              "id": 200,
              "sunday": "true",
              "Time": "10:30-11:30 AM",
              "name": "Weekly Sitting Group",
              "teacher": "Daryl Lynn Ross",
              "organization": "True North Insight Canada",
              "Registration": "YouTube"
            },
            "201": {
              "id": 201,
              "sunday": "true",
              "Time": "10:30AM-12:00 PM",
              "name": "The Circle of Stillness",
              "teacher": "Nanci Edgcomb, Various Teachers",
              "organization": "Insight Chicago Meditation Community",
              "orgUrl": "https://www.insightchicago.org/lake-forest-meditation-sangha",
              "Registration": "Zoom"
            },
            "202": {
              "id": 202,
              "sunday": "true",
              "Time": "11:00-12:00 PM",
              "name": "Virtual Meditation Town Hall",
              "teacher": "Lama Surya Das",
              "organization": "Dzogchen Center",
              "orgUrl": "https://dzogchen.org/",
              "Registration": "Zoom",
              "Registration URL": "http://www.surya.org/?utm_source=Opportunities+For+Practice+with+Lama+Surya+Das-March+2020&utm_campaign=Practice+Opportunities+Email&utm_medium=email"
            },
            "203": {
              "id": 203,
              "sunday": "true",
              "Time": "11:00AM-1:00 PM",
              "name": "Sutra Service and Meditation Practice",
              "teacher": "Rev. Jay Rinsen Weik Roshi, Rev. Karen Do'on Weik Osho",
              "organization": "Buddhist Temple of Toledo",
              "Registration": "Livestream on Facebook"
            },
            "204": {
              "id": 204,
              "sunday": "true",
              "Time": "11:30-2:45 PM",
              "name": "Virtual Sangha el Domingo - en Espanol",
              "teacher": "Various Teachers",
              "organization": "Dhamma Madrid",
              "Registration": "Zoom"
            },
            "205": {
              "id": 205,
              "sunday": "true",
              "Time": "11:30-12:45 PM",
              "name": "Weekly Practice Group",
              "teacher": "Mark Nunberg",
              "organization": "Common Ground",
              "Registration": "You Tube"
            },
            "206": {
              "id": 206,
              "sunday": "true",
              "Time": "12:00PM-1:30PM",
              "name": "Walking the Buddha's Path Together",
              "teacher": "Lisa Kring",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "207": {
              "id": 207,
              "sunday": "true",
              "Time": "12:00PM-3:00PM",
              "name": "Gay Buddhist Fellowship",
              "teacher": "Various Teachers",
              "organization": "Gay Buddhist Fellowship",
              "Registration": "Zoom"
            },
            "208": {
              "id": 208,
              "sunday": "true",
              "Time": "12:25PM-1:45 PM",
              "name": "Sitting and Talk",
              "teacher": "Gil Fronsdal",
              "organization": "Insight Meditation Center",
              "Registration": "YouTube"
            },
            "209": {
              "id": 209,
              "sunday": "true",
              "Time": "1:00-2:30 PM",
              "name": "Sunday Group",
              "teacher": "Various Teachers",
              "organization": "Seattle Insight",
              "Registration": "Zoom"
            },
            "210": {
              "id": 210,
              "sunday": "true",
              "Time": "1:00-2:30 PM",
              "name": "Sunday Sila",
              "teacher": "Sakula (Mary Reinard)",
              "organization": "Portland Friends of the Dhamma",
              "Registration": "Zoom"
            },
            "211": {
              "id": 211,
              "sunday": "true",
              "Time": "1:00-3:00PM",
              "name": "Sunday Dharma Livestream",
              "teacher": "Robert Beatty",
              "organization": "Portland Insight",
              "Registration": "Zoom"
            },
            "212": {
              "id": 212,
              "sunday": "true",
              "Time": "1:00-3:00PM",
              "name": "Dharma in Times of COVID",
              "teacher": "Various Teachers",
              "organization": "Southsea Sangha",
              "Registration": "Register Here"
            },
            "213": {
              "id": 213,
              "sunday": "true",
              "Time": "1:00-2:30 PM",
              "name": "Sunday Group",
              "teacher": "Various Teachers",
              "organization": "Seattle Insight",
              "Registration": "Zoom"
            },
            "214": {
              "id": 214,
              "sunday": "true",
              "Time": "2:00-3:30PM",
              "name": "Sunday Morning Practice Group",
              "teacher": "Trudy Goodman",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "215": {
              "id": 215,
              "sunday": "true",
              "Time": "2:00-4:00PM",
              "name": "Sunday Sangha",
              "teacher": "Various",
              "organization": "Sangha Live",
              "Registration": "Register Here"
            },
            "216": {
              "id": 216,
              "sunday": "true",
              "Time": "2:30-3:45PM",
              "name": "Virtual Sangha",
              "teacher": "Jim Forbes, Ana Monica",
              "organization": "Dhamma Madrid",
              "Registration": "Zoom"
            },
            "217": {
              "id": 217,
              "sunday": "true",
              "Time": "3:00-3:30 PM",
              "name": "Metta Meditation",
              "teacher": "Kimberly Brown",
              "organization": "Warrior Flow Foundation",
              "orgUrl": "https://www.warriorflow.com/schedule",
              "Registration": "Vimeo Livestream",
              "Registration URL": "https://vimeo.com/warriorflow"
            },
            "218": {
              "id": 218,
              "sunday": "true",
              "Time": "3:00-4:00 PM",
              "name": "Asian Sangha - 3rd Sundays",
              "teacher": "Anna Johns and Luana Long",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "219": {
              "id": 219,
              "sunday": "true",
              "Time": "4:00-5:30 PM",
              "name": "Dharma Circle for People of Asian Background, 4th Sunday",
              "teacher": "Lilu Chen, Ying Chen",
              "organization": "Insight Meditation Center",
              "Registration": "To join contact asianimc2020@gmail.com"
            },
            "220": {
              "id": 220,
              "sunday": "true",
              "Time": "6:00-7:30 PM",
              "name": "Drop-in Class",
              "teacher": "Linda Naini, Kristin Barker, Travis Spencer, Devin Maroney",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "221": {
              "id": 221,
              "sunday": "true",
              "Time": "6:00-7:30 PM",
              "name": "Every Body Every Mind Sangha (open to anyone living with disabilities, limitations, differences, chronic illnesses)",
              "teacher": "Various Teachers",
              "organization": "Every Body Every Mind Sangha",
              "Registration": "Zoom"
            },
            "222": {
              "id": 222,
              "sunday": "true",
              "Time": "7:00-8:30 PM",
              "name": "Drop-in Class",
              "teacher": "Catherine Brousseau, Deborah Ratner Helzer, Luisa Montero-Diaz, Jeff Rosenberg, Peggy O'Kane",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "223": {
              "id": 223,
              "sunday": "true",
              "Time": "7:00-8:30 PM",
              "name": "Drop-in Class",
              "teacher": "Jon Waterman, Stig Regli",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "224": {
              "id": 224,
              "sunday": "true",
              "Time": "7:00-8:30 PM",
              "name": "Drop-in Class",
              "teacher": "Jennifer Stanley",
              "organization": "Insight Meditation Center Washington",
              "Registration": "Zoom"
            },
            "225": {
              "id": 225,
              "sunday": "true",
              "Time": "7:30-9:00 PM",
              "name": "Dedicated Practice Sangha",
              "teacher": "Various Teachers",
              "organization": "New York Insight",
              "Registration": "Zoom"
            },
            "226": {
              "id": 226,
              "sunday": "true",
              "Time": "7:30-9:00 PM",
              "name": "Andersonville Sangha",
              "teacher": "Various Teachers",
              "organization": "Insight Chicago Meditation Community",
              "orgUrl": "https://www.insightchicago.org/andersonville-meditation-sangha",
              "Registration": "Go Here for Zoom Link",
              "Registration URL": "https://www.insightchicago.org/meditation-locations"
            },
            "227": {
              "id": 227,
              "sunday": "true",
              "Time": "7:00-9:00 PM",
              "name": "Sunday - Denver",
              "teacher": "Lloyd Burton",
              "organization": "Insight Meditation Community of Colorado",
              "Registration": "Zoom"
            },
            "228": {
              "id": 228,
              "sunday": "true",
              "Time": "8:00-9:30 PM",
              "name": "Insight Meditation Center Queer Dharma Group",
              "teacher": "John Martin, Bruni Davila",
              "organization": "Insight Meditation Center",
              "Registration": "Please email imcqueersangha@gmail.com to request Link"
            },
            "229": {
              "id": 229,
              "sunday": "true",
              "Time": "8:00-9:30 PM",
              "name": "Saturday Afternoon Sit and Dharma Talk",
              "teacher": "Mary Stancavage",
              "organization": "Undefended Dharma",
              "Registration": "Zoom"
            },
            "230": {
              "id": 230,
              "sunday": "true",
              "Time": "8:00-9:00 PM",
              "name": "Recovery Dharma",
              "teacher": "Peer Led",
              "organization": "SF Dharma Collective",
              "Registration": "Zoom"
            },
            "231": {
              "id": 231,
              "sunday": "true",
              "Time": "9:00-10:30 PM",
              "name": "Sunday Meeting",
              "teacher": "Wendy Palmer",
              "organization": "Marin Sangha",
              "Registration": "New Zoom Link",
              "Registration URL": "https://marinsangha.us3.list-manage.com/track/click?u=a8923be6e34759a89065a1599&id=f43a028073&e=35193a0a2a"
            },
            "232": {
              "id": 232,
              "sunday": "true",
              "Time": "9:00-10:30 PM",
              "name": "Fierce Hearts",
              "teacher": "Kara Haney",
              "organization": "Insight Santa Cruz",
              "Registration": "Zoom"
            },
            "233": {
              "id": 233,
              "sunday": "true",
              "Time": "9:00-10:30 PM",
              "name": "Sunday Sitting",
              "teacher": "Eugene Cash and others",
              "organization": "SF Insight",
              "Registration": "Zoom"
            },
            "234": {
              "id": 234,
              "sunday": "true",
              "Time": "9:30-11:00 PM",
              "name": "Meditation Coalition People of Color Sangha",
              "teacher": "Eileen Ybarra, Amy Love, Elliott Law",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "235": {
              "id": 235,
              "sunday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Alameda Sangha",
              "teacher": "Rebecca Dixon, Deb Kerr",
              "organization": "Alameda Sangha"
            },
            "236": {
              "id": 236,
              "sunday": "true",
              "Time": "10:00PM-12:00 AM",
              "name": "Sunday Sangha",
              "teacher": "Will Kabat-Zinn",
              "organization": "Sunday Sangha",
              "Registration": "Zoom"
            },
            "237": {
              "id": 237,
              "sunday": "true",
              "Time": "10:00-11:30 PM",
              "name": "The Dharma Doors",
              "teacher": "MC Owens",
              "organization": "SF Dharma Collective",
              "Registration": "Zoom"
            },
            "238": {
              "id": 238,
              "sunday": "true",
              "Time": "10:30-12:00 AM",
              "name": "Dhamma Evening for People in their 20's & 30's",
              "teacher": "Max Erdstein",
              "organization": "Insight Meditation Center",
              "Registration": "Zoom"
            },
            "239": {
              "id": 239,
              "sunday": "true",
              "Time": "10:00-11:30 PM",
              "name": "Youngish Adult (20's & 30's) Practice Group",
              "teacher": "Various Teachers",
              "organization": "Insight L.A.",
              "Registration": "Zoom"
            },
            "240": {
              "id": 240,
              "sunday": "true",
              "Time": "10:30-12:00 AM",
              "name": "Buddhism and Twelve Step Support Group, 2nd Sundays",
              "teacher": "Jennifer Lemas",
              "organization": "Insight Meditation Center",
              "Registration": "Zoom"
            }
    },
    days: {
        sunday: ['abc', 'afbc', '213'],
        monday: [],
        tuesday: [],
        wednesday: [],
        thursday: ['def', 'red', '12323'],
        friday: ['def', 'red', '12323'],
        saturday: ['def', 'red', '12323'],
    }
}

export default SANGHA_DATA;